"use server";

import { randomUUID } from "node:crypto";
import { revalidatePath } from "next/cache";
import { asc, desc, eq } from "drizzle-orm";
import { z } from "zod";
import db from "@/db/drizzle";
import { melAuditEvents, melOperationalChecks, melOperationalEvents, melRolloutControl } from "@/db/schema";
import { requireMelManager, requireMelViewer } from "@/lib/mel/access";
import { errorResponse, successResponse, type ActionResponse } from "./types";

const DEFAULT_CHECKS = [
  ["itt_reconciliation", "quality", "ITT reconciliation pack signed"], ["security_review", "security", "Critical and high security findings resolved"], ["internal_uat", "rollout", "Internal MEL/admin UAT accepted"], ["backup_restore", "recovery", "Non-production restore test passed"], ["pilot_uat", "rollout", "Pilot acceptance completed"], ["training_complete", "handover", "Role-based training completed"], ["load_test", "performance", "Expected-scale load test passed"], ["accessibility_audit", "accessibility", "Mobile and accessibility audit passed"], ["runbook_acceptance", "handover", "Operational owners accepted runbooks"], ["stabilization_closed", "rollout", "Stabilization window closed within service levels"],
] as const;
const stageRequirements: Record<string, string[]> = { internal_test: [], pilot: ["itt_reconciliation", "security_review", "internal_uat"], programme_rollout: ["backup_restore", "pilot_uat", "training_complete"], stabilization: ["load_test", "accessibility_audit", "runbook_acceptance"], complete: ["stabilization_closed"] };
function failure(error: unknown, fallback: string): ActionResponse<never> { if (error instanceof z.ZodError) return errorResponse(error.issues[0]?.message ?? fallback); if (error instanceof Error) return errorResponse(error.message); return errorResponse(fallback); }

async function ensureChecks() { const existing = await db.select({ code: melOperationalChecks.code }).from(melOperationalChecks); const codes = new Set(existing.map((item) => item.code)); const missing = DEFAULT_CHECKS.filter(([code]) => !codes.has(code)); if (missing.length) await db.insert(melOperationalChecks).values(missing.map(([code, category, name]) => ({ code, category, name }))); }

export async function getMelOperationsWorkspace() {
  try { const actor = await requireMelViewer(); await ensureChecks(); const [rollout, checks, events] = await Promise.all([db.query.melRolloutControl.findFirst({ where: eq(melRolloutControl.id, 1) }), db.select().from(melOperationalChecks).orderBy(asc(melOperationalChecks.category), asc(melOperationalChecks.name)), db.select().from(melOperationalEvents).orderBy(desc(melOperationalEvents.createdAt)).limit(100)]); return successResponse({ canManage: actor.canManage, rollout: rollout ?? { id: 1, stage: "internal_test" as const, collectionEnabled: false, importsEnabled: false, reportingEnabled: false, pilotCountyCodes: [], rollbackReason: null, updatedById: null, updatedAt: new Date() }, checks, events }); } catch (error) { return failure(error, "Unable to load MEL operational readiness."); }
}

export async function updateMelOperationalCheckAction(input: { checkId: number; status: "not_started" | "in_progress" | "passed" | "failed" | "waived"; owner?: string; evidence?: string; notes?: string }) {
  try { const actor = await requireMelManager(); const value = z.object({ checkId: z.number().int().positive(), status: z.enum(["not_started", "in_progress", "passed", "failed", "waived"]), owner: z.string().trim().max(180).optional(), evidence: z.string().trim().max(4000).optional(), notes: z.string().trim().max(4000).optional() }).parse(input); if (["passed", "waived"].includes(value.status) && (value.evidence?.length ?? 0) < 10) throw new Error("Passed or waived checks require evidence of at least 10 characters."); await db.update(melOperationalChecks).set({ status: value.status, owner: value.owner || null, evidence: value.evidence || null, notes: value.notes || null, verifiedById: ["passed", "waived"].includes(value.status) ? actor.id : null, verifiedAt: ["passed", "waived"].includes(value.status) ? new Date() : null, updatedAt: new Date() }).where(eq(melOperationalChecks.id, value.checkId)); revalidatePath("/admin/mel/operations"); return successResponse({ id: value.checkId }, "Operational check updated."); } catch (error) { return failure(error, "Unable to update operational check."); }
}

export async function updateMelRolloutControlAction(input: { stage: "internal_test" | "pilot" | "programme_rollout" | "stabilization" | "complete"; collectionEnabled: boolean; importsEnabled: boolean; reportingEnabled: boolean; pilotCountyCodes: string[]; rollbackReason?: string }) {
  try { const actor = await requireMelManager(); const value = z.object({ stage: z.enum(["internal_test", "pilot", "programme_rollout", "stabilization", "complete"]), collectionEnabled: z.boolean(), importsEnabled: z.boolean(), reportingEnabled: z.boolean(), pilotCountyCodes: z.array(z.string().min(1).max(80)).max(47), rollbackReason: z.string().trim().max(2000).optional() }).parse(input); await ensureChecks(); const [current, checks] = await Promise.all([db.query.melRolloutControl.findFirst({ where: eq(melRolloutControl.id, 1) }), db.select().from(melOperationalChecks)]); const order = ["internal_test", "pilot", "programme_rollout", "stabilization", "complete"]; if (current && order.indexOf(value.stage) < order.indexOf(current.stage) && (value.rollbackReason?.length ?? 0) < 10) throw new Error("Rolling back a stage requires a reason of at least 10 characters."); const unmet = (stageRequirements[value.stage] ?? []).filter((code) => !checks.some((check) => check.code === code && ["passed", "waived"].includes(check.status))); if (unmet.length) throw new Error(`Complete the required gates first: ${unmet.join(", ")}.`); if (value.stage === "pilot" && value.pilotCountyCodes.length === 0) throw new Error("Select at least one pilot county."); await db.transaction(async (tx) => { await tx.insert(melRolloutControl).values({ id: 1, ...value, rollbackReason: value.rollbackReason || null, updatedById: actor.id, updatedAt: new Date() }).onConflictDoUpdate({ target: melRolloutControl.id, set: { ...value, rollbackReason: value.rollbackReason || null, updatedById: actor.id, updatedAt: new Date() } }); await tx.insert(melAuditEvents).values({ actorId: actor.id, actorRole: actor.role, entityType: "mel_rollout_control", entityId: "1", action: "updated", reason: value.rollbackReason || null, before: current ? { stage: current.stage, collectionEnabled: current.collectionEnabled, importsEnabled: current.importsEnabled, reportingEnabled: current.reportingEnabled } : null, after: value, correlationId: randomUUID() }); }); revalidatePath("/admin/mel/operations"); return successResponse({ stage: value.stage }, "Rollout controls updated."); } catch (error) { return failure(error, "Unable to update rollout controls."); }
}

export async function resolveMelOperationalEventAction(eventId: number) { try { const actor = await requireMelManager(); await db.update(melOperationalEvents).set({ resolvedAt: new Date(), resolvedById: actor.id }).where(eq(melOperationalEvents.id, eventId)); revalidatePath("/admin/mel/operations"); return successResponse({ id: eventId }, "Operational event resolved."); } catch (error) { return failure(error, "Unable to resolve operational event."); } }
