"use server";

import { createHash, randomBytes, randomUUID } from "node:crypto";
import { revalidatePath } from "next/cache";
import { asc, desc, eq } from "drizzle-orm";
import { z } from "zod";
import db from "@/db/drizzle";
import { melAuditEvents, melImportBatches, melImportMappings, melImportRecords, melInstrumentSubmissions, melInstrumentVersions, melIntegrationConnections } from "@/db/schema";
import { requireMelManager, requireMelViewer } from "@/lib/mel/access";
import { loadInstrumentDefinition } from "@/lib/mel/instrument-data";
import { validateInstrumentResponses } from "@/lib/mel/instrument-engine";
import { ingestMelIntegrationPayload } from "@/lib/mel/import-service";
import { errorResponse, successResponse, type ActionResponse } from "./types";

const connectionSchema = z.object({ name: z.string().trim().min(3).max(180), provider: z.enum(["kobo", "odk", "file", "legacy"]), instrumentVersionId: z.number().int().positive(), externalFormId: z.string().trim().max(255).optional() });
const mappingSchema = z.object({ connectionId: z.number().int().positive(), enterpriseIdField: z.string().trim().min(1).max(150), reportingPeriodField: z.string().trim().min(1).max(150), externalSubmissionIdField: z.string().trim().min(1).max(150), fieldMap: z.record(z.string(), z.string()) });
function failure(error: unknown, fallback: string): ActionResponse<never> { if (error instanceof z.ZodError) return errorResponse(error.issues[0]?.message ?? fallback); if (error instanceof Error) return errorResponse(error.message); return errorResponse(fallback); }
const secretHash = (secret: string) => createHash("sha256").update(secret).digest("hex");

export async function getMelImportWorkspace() {
  try { const actor = await requireMelViewer(); const [connections, mappings, batches, records, versions] = await Promise.all([db.select().from(melIntegrationConnections).orderBy(asc(melIntegrationConnections.name)), db.select().from(melImportMappings).orderBy(desc(melImportMappings.version)), db.select().from(melImportBatches).orderBy(desc(melImportBatches.createdAt)).limit(100), db.select().from(melImportRecords).orderBy(desc(melImportRecords.createdAt)).limit(250), db.query.melInstrumentVersions.findMany({ where: eq(melInstrumentVersions.status, "published"), with: { instrument: true }, orderBy: [desc(melInstrumentVersions.publishedAt)] })]); return successResponse({ canManage: actor.canManage, connections: connections.map((connection) => ({ ...connection, mappings: mappings.filter((mapping) => mapping.connectionId === connection.id) })), batches, records, versions }); } catch (error) { return failure(error, "Unable to load MEL imports."); }
}

export async function createMelIntegrationConnectionAction(input: unknown) {
  try { const actor = await requireMelManager(); const value = connectionSchema.parse(input); const version = await db.query.melInstrumentVersions.findFirst({ where: eq(melInstrumentVersions.id, value.instrumentVersionId) }); if (!version || version.status !== "published") throw new Error("Integrations require a published instrument version."); const secret = `mel_${randomBytes(24).toString("base64url")}`; const [connection] = await db.insert(melIntegrationConnections).values({ ...value, externalFormId: value.externalFormId || null, secretHash: secretHash(secret), createdById: actor.id }).returning({ id: melIntegrationConnections.id }); await db.insert(melAuditEvents).values({ actorId: actor.id, actorRole: actor.role, entityType: "mel_integration_connection", entityId: String(connection.id), action: "created", after: { provider: value.provider, instrumentVersionId: value.instrumentVersionId }, correlationId: randomUUID() }); revalidatePath("/admin/mel/imports"); return successResponse({ id: connection.id, secret }, "Connection created. Copy the webhook secret now; it will not be shown again."); } catch (error) { return failure(error, "Unable to create integration connection."); }
}

export async function saveMelImportMappingAction(input: unknown) {
  try { const actor = await requireMelManager(); const value = mappingSchema.parse(input); const existing = await db.query.melImportMappings.findMany({ where: eq(melImportMappings.connectionId, value.connectionId), orderBy: (table, { desc: descending }) => [descending(table.version)] }); const version = (existing[0]?.version ?? 0) + 1; await db.transaction(async (tx) => { await tx.update(melImportMappings).set({ isActive: false }).where(eq(melImportMappings.connectionId, value.connectionId)); await tx.insert(melImportMappings).values({ ...value, version, createdById: actor.id }); await tx.insert(melAuditEvents).values({ actorId: actor.id, actorRole: actor.role, entityType: "mel_import_mapping", entityId: String(value.connectionId), action: "version_created", after: { version, mappedFieldCount: Object.keys(value.fieldMap).length }, correlationId: randomUUID() }); }); revalidatePath("/admin/mel/imports"); return successResponse({ version }, "Import mapping version saved."); } catch (error) { return failure(error, "Unable to save import mapping."); }
}

export async function testMelImportPayloadAction(connectionId: number, payloadText: string) {
  try { await requireMelManager(); const payload = z.record(z.string(), z.unknown()).parse(JSON.parse(payloadText)); return successResponse(await ingestMelIntegrationPayload(connectionId, payload, "controlled test"), "Test payload processed."); } catch (error) { return failure(error, "Unable to process test payload."); }
}

export async function promoteMelImportRecordAction(recordId: number) {
  try {
    const actor = await requireMelManager(); const record = await db.query.melImportRecords.findFirst({ where: eq(melImportRecords.id, recordId) }); if (!record || record.status !== "validated" || !record.businessId || !record.reportingPeriodId || !record.connectionId || !record.normalizedPayload) throw new Error("Only a fully validated import can be promoted."); const connection = await db.query.melIntegrationConnections.findFirst({ where: eq(melIntegrationConnections.id, record.connectionId) }); if (!connection) throw new Error("Import connection is unavailable."); const definition = await loadInstrumentDefinition(connection.instrumentVersionId); const responseErrors = validateInstrumentResponses(definition, record.normalizedPayload); if (Object.keys(responseErrors).length) { await db.update(melImportRecords).set({ status: "quarantined", validationErrors: Object.entries(responseErrors).map(([code, message]) => `${code}: ${message}`), attempts: record.attempts + 1, updatedAt: new Date() }).where(eq(melImportRecords.id, recordId)); return errorResponse("The mapped response failed instrument validation and was returned to quarantine."); }
    const submissionId = await db.transaction(async (tx) => { const [submission] = await tx.insert(melInstrumentSubmissions).values({ instrumentVersionId: connection.instrumentVersionId, businessId: record.businessId!, reportingPeriodId: record.reportingPeriodId!, collectorId: actor.id, status: "submitted", responseData: record.normalizedPayload!, importRecordId: record.id, submittedAt: new Date() }).returning({ id: melInstrumentSubmissions.id }); await tx.update(melImportRecords).set({ status: "promoted", promotedSubmissionId: submission.id, reviewedById: actor.id, reviewedAt: new Date(), updatedAt: new Date() }).where(eq(melImportRecords.id, recordId)); await tx.insert(melAuditEvents).values({ actorId: actor.id, actorRole: actor.role, entityType: "mel_import_record", entityId: String(recordId), action: "promoted_to_review", after: { submissionId: submission.id }, correlationId: randomUUID() }); return submission.id; }); revalidatePath("/admin/mel/imports"); return successResponse({ submissionId }, "Imported record promoted to the normal review status. It was not auto-approved.");
  } catch (error) { return failure(error, "Unable to promote imported record."); }
}

export async function reviewMelInstrumentSubmissionAction(submissionId: number, decision: "approve" | "return", reason: string) {
  try { const actor = await requireMelManager(); const submission = await db.query.melInstrumentSubmissions.findFirst({ where: eq(melInstrumentSubmissions.id, submissionId) }); if (!submission || !["submitted", "resubmitted"].includes(submission.status)) throw new Error("Submission is not awaiting review."); if (submission.collectorId === actor.id) throw new Error("Collectors cannot approve or return their own imported submission."); if (decision === "return" && reason.trim().length < 10) throw new Error("Provide a correction reason of at least 10 characters."); const status = decision === "approve" ? "approved" : "returned_by_mel"; await db.transaction(async (tx) => { await tx.update(melInstrumentSubmissions).set({ status, approvedAt: decision === "approve" ? new Date() : null, approvedById: decision === "approve" ? actor.id : null, returnReason: decision === "return" ? reason : null, updatedAt: new Date() }).where(eq(melInstrumentSubmissions.id, submissionId)); await tx.insert(melAuditEvents).values({ actorId: actor.id, actorRole: actor.role, entityType: "mel_instrument_submission", entityId: String(submissionId), action: decision, reason: reason || null, before: { status: submission.status }, after: { status }, correlationId: randomUUID() }); }); revalidatePath("/admin/mel/imports"); return successResponse({ submissionId }, `Submission ${decision === "approve" ? "approved" : "returned"}.`); } catch (error) { return failure(error, "Unable to review instrument submission."); }
}
