"use client";

import { useState, useTransition } from "react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { addMelInstrumentQuestionAction, addMelInstrumentSectionAction, createMelInstrumentAction, createNextMelInstrumentVersionAction, getMelInstrumentWorkspace, publishMelInstrumentVersionAction, retireMelInstrumentVersionAction } from "@/lib/actions/mel-instruments";

type Workspace = NonNullable<Awaited<ReturnType<typeof getMelInstrumentWorkspace>>["data"]>;
const control = "h-10 w-full rounded-md border border-slate-300 bg-background px-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-brand-blue/40";

export function InstrumentAdminWorkspace({ data }: { data: Workspace }) {
  const [pending, start] = useTransition(); const [selectedVersion, setSelectedVersion] = useState<number | null>(data.instruments.flatMap((item) => item.versions).find((item) => item.status === "draft")?.id ?? null); const [selectedSection, setSelectedSection] = useState<number | null>(null); const [retireReason, setRetireReason] = useState("");
  const act = (work: () => Promise<{ success: boolean; message?: string; error?: string }>) => start(async () => { const result = await work(); if (result.success) toast.success(result.message); else toast.error(result.error); });
  const versions = data.instruments.flatMap((instrument) => instrument.versions.map((version) => ({ ...version, instrument })));
  const version = versions.find((item) => item.id === selectedVersion);
  return <div className="space-y-6">
    {data.canManage ? <form onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); act(() => createMelInstrumentAction({ code: form.get("code"), name: form.get("name"), description: form.get("description"), type: form.get("type") })); }} className="grid gap-3 rounded-lg border border-slate-200 bg-slate-50/70 p-4 md:grid-cols-4"><Field label="Instrument code"><input name="code" required placeholder="BIRE_BASELINE" className={control} /></Field><Field label="Name"><input name="name" required className={control} /></Field><Field label="Type"><select name="type" className={control}>{["baseline", "quarterly_monitoring", "midline", "endline", "special_study"].map((type) => <option key={type} value={type}>{human(type)}</option>)}</select></Field><Field label="Description"><input name="description" className={control} /></Field><div className="md:col-span-4"><Button disabled={pending}>Create draft instrument</Button></div></form> : null}
    <div className="grid gap-5 xl:grid-cols-[300px_1fr]"><aside className="rounded-lg border border-slate-200 bg-background"><div className="border-b p-4"><h2 className="font-semibold text-slate-900">Instrument versions</h2></div><ul className="divide-y">{versions.map((item) => <li key={item.id}><button type="button" onClick={() => { setSelectedVersion(item.id); setSelectedSection(item.sections[0]?.id ?? null); }} className={`w-full px-4 py-3 text-left hover:bg-slate-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-brand-blue/40 ${item.id === selectedVersion ? "bg-brand-blue/5" : ""}`}><div className="flex items-center justify-between gap-2"><span className="font-medium text-slate-900">{item.instrument.name}</span><Badge variant="outline">v{item.version}</Badge></div><p className="mt-1 text-xs text-slate-500">{item.status} · {item.sections.length} sections</p></button></li>)}</ul>{versions.length === 0 ? <p className="p-6 text-center text-sm text-slate-500">Create the first instrument draft.</p> : null}</aside>
      <main className="space-y-5">{version ? <><header className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-brand-blue">{version.instrument.code} · version {version.version}</p><h2 className="mt-1 text-xl font-bold text-slate-900">{version.instrument.name}</h2><p className="text-sm text-slate-600">{version.status === "draft" ? "Editable draft" : "Immutable published definition"}</p></div>{data.canManage ? <div className="flex flex-wrap gap-2">{version.status === "draft" ? <><Button variant="outline" disabled={pending} onClick={() => act(() => publishMelInstrumentVersionAction(version.id, null))}>Validate and publish</Button></> : <Button variant="outline" disabled={pending} onClick={() => act(() => createNextMelInstrumentVersionAction(version.instrumentId))}>Create next version</Button>}{version.status === "published" ? <><input value={retireReason} onChange={(event) => setRetireReason(event.target.value)} placeholder="Retirement reason" className={`${control} w-52`} /><Button variant="destructive" disabled={pending} onClick={() => act(() => retireMelInstrumentVersionAction(version.id, retireReason))}>Retire</Button></> : null}</div> : null}</header>
        {data.canManage && version.status === "draft" ? <form onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); act(() => addMelInstrumentSectionAction({ versionId: version.id, code: form.get("code"), title: form.get("title"), description: form.get("description"), sortOrder: Number(form.get("sortOrder")) })); }} className="grid gap-3 rounded-lg border border-slate-200 p-4 sm:grid-cols-4"><Field label="Section code"><input name="code" required className={control} /></Field><Field label="Title"><input name="title" required className={control} /></Field><Field label="Description"><input name="description" className={control} /></Field><Field label="Order"><input name="sortOrder" type="number" min="0" defaultValue={version.sections.length} className={control} /></Field><div className="sm:col-span-4"><Button size="sm" disabled={pending}>Add section</Button></div></form> : null}
        <div className="space-y-3">{version.sections.map((section) => <section key={section.id} className="rounded-lg border border-slate-200 bg-background"><button type="button" onClick={() => setSelectedSection(section.id === selectedSection ? null : section.id)} className="flex w-full items-center justify-between px-4 py-3 text-left"><span><span className="font-semibold text-slate-900">{section.title}</span><span className="ml-2 text-xs text-slate-500">{section.code}</span></span><span className="text-xs text-slate-500">{section.questions.length} questions</span></button>{selectedSection === section.id ? <div className="border-t p-4"><ol className="space-y-2">{section.questions.map((question) => <li key={question.id} className="rounded-md bg-slate-50 px-3 py-2 text-sm"><div className="flex items-start justify-between gap-3"><span><span className="font-medium text-slate-900">{question.label}</span><span className="ml-2 text-xs text-slate-500">{question.code}</span></span><Badge variant="outline">{human(question.responseType)}</Badge></div>{question.visibilityRule ? <p className="mt-1 text-xs text-slate-500">Visible when {question.visibilityRule.questionCode} {human(question.visibilityRule.operator)} {String(question.visibilityRule.value ?? "answered")}</p> : null}</li>)}</ol>{data.canManage && version.status === "draft" ? <QuestionForm sectionId={section.id} count={section.questions.length} indicators={data.indicators} submit={(input) => act(() => addMelInstrumentQuestionAction(input))} pending={pending} /> : null}</div> : null}</section>)}</div></> : <p className="rounded-lg border p-8 text-center text-sm text-slate-500">Select an instrument version.</p>}</main></div>
  </div>;
}

function QuestionForm({ sectionId, count, indicators, submit, pending }: { sectionId: number; count: number; indicators: Workspace["indicators"]; submit: (input: unknown) => void; pending: boolean }) { return <form onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const options = String(form.get("options") ?? "").split(",").map((value) => value.trim()).filter(Boolean).map((value) => ({ value, label: value })); const dependency = String(form.get("dependency") ?? "").trim(); submit({ sectionId, code: form.get("code"), label: form.get("label"), responseType: form.get("responseType"), isRequired: form.get("required") === "on", helpText: form.get("helpText"), options, visibilityRule: dependency ? { questionCode: dependency, operator: "equals", value: String(form.get("dependencyValue") ?? "") } : null, validationRules: {}, indicatorId: Number(form.get("indicatorId")) || null, evidenceRequired: form.get("evidenceRequired") === "on", sortOrder: count }); }} className="mt-4 grid gap-3 border-t pt-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="Question code"><input name="code" required className={control} /></Field><Field label="Question label"><input name="label" required className={control} /></Field><Field label="Response type"><select name="responseType" className={control}>{["short_text", "long_text", "integer", "decimal", "currency", "percentage", "date", "boolean", "single_select", "multi_select", "file"].map((type) => <option key={type} value={type}>{human(type)}</option>)}</select></Field><Field label="Options (comma separated)"><input name="options" className={control} /></Field><Field label="Indicator mapping"><select name="indicatorId" className={control}><option value="">No mapping</option>{indicators.map((item) => <option key={item.id} value={item.id}>{item.code} ({item.unit})</option>)}</select></Field><Field label="Visible when question"><input name="dependency" className={control} /></Field><Field label="Equals value"><input name="dependencyValue" className={control} /></Field><Field label="Help text"><input name="helpText" className={control} /></Field><label className="flex items-center gap-2 text-sm"><input name="required" type="checkbox" /> Required</label><label className="flex items-center gap-2 text-sm"><input name="evidenceRequired" type="checkbox" /> Evidence required</label><div className="sm:col-span-2"><Button size="sm" disabled={pending}>Add question</Button></div></form>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="space-y-1.5 text-sm font-medium text-slate-700"><span>{label}</span>{children}</label>; }
function human(value: string) { return value.replaceAll("_", " "); }
