import { MEL_OP11_MOBILISATION_TARGETS } from "./programme-calendar";

export type MelSeedBaseline = {
  segmentKey: string;
  value?: number;
  valueText?: string;
  notes?: string;
};

export type MelSeedTarget = {
  programmeYear: number;
  segmentKey?: string;
  value?: number;
  valueText?: string;
  notes?: string;
};

export type MelSeedIndicator = {
  code: string;
  resultCode: string;
  resultLevel: "impact" | "long_term_outcome" | "output" | "operational";
  resultStatement: string;
  name: string;
  definition?: string;
  unit: "count" | "kes" | "percentage" | "kilograms" | "status" | "score";
  sourceType: "system" | "quarterly_enterprise_form" | "programme_mel_entry" | "integration" | "derived";
  frequency: string;
  aggregation: "sum" | "median" | "count" | "distinct_count" | "ratio" | "latest_value";
  numeratorDefinition?: string;
  denominatorDefinition?: string;
  disaggregationDimensions: string[];
  evidenceRequired: boolean;
  isOneTime: boolean;
  sortOrder: number;
  unresolvedNotes?: string;
  baselines?: MelSeedBaseline[];
  targets?: MelSeedTarget[];
};

const enterpriseDimensions = ["track", "owner_gender", "owner_youth", "owner_plwd", "county", "sector"];
const jobDimensions = [
  "track",
  "job_type",
  "job_holder_gender",
  "job_holder_youth",
  "job_holder_plwd",
  "county",
  "sector",
];

const ratioDefinition = (result: string, denominator: string) => ({
  definition: `${result} as a share of ${denominator}.`,
  numeratorDefinition: result,
  denominatorDefinition: denominator,
});

export const MEL_ITT_SEED: MelSeedIndicator[] = [
  {
    code: "IM-JOBS-CREATED",
    resultCode: "IM",
    resultLevel: "impact",
    resultStatement: "Improved livelihoods through sustainable enterprise development in Kenya",
    name: "Number of jobs created",
    definition: "New direct and indirect jobs created after the programme baseline.",
    unit: "count",
    sourceType: "quarterly_enterprise_form",
    frequency: "quarterly",
    aggregation: "sum",
    disaggregationDimensions: jobDimensions,
    evidenceRequired: true,
    isOneTime: false,
    sortOrder: 10,
    baselines: [{ segmentKey: "overall", valueText: "N/A" }],
    targets: [
      { programmeYear: 0, value: 6800 },
      { programmeYear: 0, segmentKey: "job_type:direct", value: 2000 },
      { programmeYear: 0, segmentKey: "job_type:indirect", value: 4800 },
      { programmeYear: 1, value: 1224 },
      { programmeYear: 1, segmentKey: "job_type:direct", value: 360 },
      { programmeYear: 1, segmentKey: "job_type:indirect", value: 864 },
      { programmeYear: 2, value: 2720 },
      { programmeYear: 2, segmentKey: "job_type:direct", value: 800 },
      { programmeYear: 2, segmentKey: "job_type:indirect", value: 1920 },
      { programmeYear: 3, value: 2856 },
      { programmeYear: 3, segmentKey: "job_type:direct", value: 840 },
      { programmeYear: 3, segmentKey: "job_type:indirect", value: 2016 },
    ],
  },
  {
    code: "LT1-PROFITABILITY-INCREASE",
    resultCode: "LT1",
    resultLevel: "long_term_outcome",
    resultStatement: "Increased commercialization and scale-up of supported MSEs across sectors",
    name: "Percentage increase in enterprise profitability",
    definition:
      "Growth in the cohort median monthly-equivalent enterprise profit compared with the approved baseline median.",
    unit: "percentage",
    sourceType: "derived",
    frequency: "quarterly",
    aggregation: "median",
    disaggregationDimensions: enterpriseDimensions,
    evidenceRequired: false,
    isOneTime: false,
    sortOrder: 20,
    unresolvedNotes:
      "The ITT also lists an overall KES endline value of 1,200,000. Keep it as a target note until MEL confirms whether it is a secondary target.",
    baselines: [
      {
        segmentKey: "overall",
        valueText: "Track-specific baseline required",
        notes: "Overall comparison is unavailable. View Foundation and Acceleration separately.",
      },
      { segmentKey: "track:foundation", value: 50000, notes: "Validated monthly profitability baseline" },
      { segmentKey: "track:acceleration", value: 150000, notes: "Validated monthly profitability baseline" },
    ],
    targets: [
      { programmeYear: 0, value: 50, notes: "Overall growth target; ITT also notes KES 1,200,000." },
      { programmeYear: 1, valueText: "KES 900,000 median monthly-equivalent profit" },
      { programmeYear: 2, valueText: "KES 1,000,000 median monthly-equivalent profit" },
      { programmeYear: 3, valueText: "KES 1,200,000 median monthly-equivalent profit" },
    ],
  },
  {
    code: "LT2-NEW-MARKETS",
    resultCode: "LT2",
    resultLevel: "long_term_outcome",
    resultStatement: "Increased access to market information and financial services for MSEs",
    name: "Percentage of enterprises accessing new markets",
    ...ratioDefinition("Distinct approved enterprises that accessed a new market", "Eligible supported enterprises"),
    unit: "percentage",
    sourceType: "quarterly_enterprise_form",
    frequency: "quarterly",
    aggregation: "ratio",
    disaggregationDimensions: enterpriseDimensions,
    evidenceRequired: false,
    isOneTime: false,
    sortOrder: 30,
    baselines: [
      { segmentKey: "overall", value: 87 },
      { segmentKey: "track:foundation", value: 89 },
      { segmentKey: "track:acceleration", value: 86 },
    ],
    targets: [
      { programmeYear: 0, value: 100 },
      { programmeYear: 2, value: 95 },
      { programmeYear: 3, value: 100 },
    ],
  },
  {
    code: "LT2-FINANCIAL-RESILIENCE",
    resultCode: "LT2",
    resultLevel: "long_term_outcome",
    resultStatement: "Increased access to market information and financial services for MSEs",
    name: "Percentage of financially resilient enterprises",
    ...ratioDefinition("Enterprises meeting the approved financial resilience definition", "Eligible supported enterprises"),
    unit: "percentage",
    sourceType: "derived",
    frequency: "quarterly",
    aggregation: "ratio",
    disaggregationDimensions: enterpriseDimensions,
    evidenceRequired: false,
    isOneTime: false,
    sortOrder: 40,
    unresolvedNotes: "MEL must approve the financially resilient enterprise definition before activation.",
    baselines: [
      { segmentKey: "overall", value: 9 },
      { segmentKey: "track:foundation", value: 10 },
      { segmentKey: "track:acceleration", value: 8 },
    ],
    targets: [
      { programmeYear: 0, value: 30 },
      { programmeYear: 2, value: 20 },
      { programmeYear: 3, value: 30 },
    ],
  },
  {
    code: "LT3-CIRCULAR-GROWTH",
    resultCode: "LT3",
    resultLevel: "long_term_outcome",
    resultStatement: "Increased adoption of circular economy models and social safeguards by MSEs",
    name: "Percentage of enterprises reporting circular-economy cost savings or revenue growth",
    ...ratioDefinition(
      "Enterprises with approved cost savings or revenue growth attributed to circular economy practices",
      "Eligible supported enterprises"
    ),
    unit: "percentage",
    sourceType: "quarterly_enterprise_form",
    frequency: "quarterly",
    aggregation: "ratio",
    disaggregationDimensions: enterpriseDimensions,
    evidenceRequired: true,
    isOneTime: false,
    sortOrder: 50,
    baselines: [
      { segmentKey: "overall", value: 80 },
      { segmentKey: "track:foundation", value: 81 },
      { segmentKey: "track:acceleration", value: 79 },
    ],
    targets: [
      { programmeYear: 0, value: 95 },
      { programmeYear: 2, value: 90 },
      { programmeYear: 3, value: 95 },
    ],
  },
  {
    code: "LT4-POLICY-ENVIRONMENT",
    resultCode: "LT4",
    resultLevel: "long_term_outcome",
    resultStatement: "Strengthened systems and capacity of sector actors to support sustainable enterprise development",
    name: "Percentage of sector institutions reporting an efficient policy environment",
    ...ratioDefinition(
      "Surveyed sector institutions reporting an efficient policy environment",
      "Eligible sector institutions responding to the approved instrument"
    ),
    unit: "percentage",
    sourceType: "programme_mel_entry",
    frequency: "annual",
    aggregation: "ratio",
    disaggregationDimensions: ["institution_type", "county"],
    evidenceRequired: true,
    isOneTime: false,
    sortOrder: 60,
    unresolvedNotes: "Confirm the source instrument, eligible institution population, and reporting frequency.",
    baselines: [
      { segmentKey: "overall", value: 43 },
      { segmentKey: "track:foundation", value: 39 },
      { segmentKey: "track:acceleration", value: 48 },
    ],
    targets: [
      { programmeYear: 0, value: 70 },
      { programmeYear: 2, value: 60 },
      { programmeYear: 3, value: 70 },
    ],
  },
  {
    code: "OP1.1-ENTERPRISES-MOBILISED",
    resultCode: "OP1.1",
    resultLevel: "output",
    resultStatement: "MSEs mobilized",
    name: "Number of enterprises mobilized",
    unit: "count",
    sourceType: "system",
    frequency: "annual",
    aggregation: "distinct_count",
    disaggregationDimensions: enterpriseDimensions,
    evidenceRequired: false,
    isOneTime: true,
    sortOrder: 100,
    baselines: [{ segmentKey: "overall", value: 0 }],
    targets: [
      { programmeYear: 0, value: MEL_OP11_MOBILISATION_TARGETS.overall },
      { programmeYear: 1, value: MEL_OP11_MOBILISATION_TARGETS.year1 },
      { programmeYear: 2, value: MEL_OP11_MOBILISATION_TARGETS.year2 },
      { programmeYear: 3, value: MEL_OP11_MOBILISATION_TARGETS.year3 },
    ],
  },
  {
    code: "OP1.1-CNA-COMPLETED",
    resultCode: "OP1.1",
    resultLevel: "output",
    resultStatement: "MSEs mobilized",
    name: "Number of Capacity Needs Assessments completed",
    unit: "count",
    sourceType: "system",
    frequency: "annual",
    aggregation: "distinct_count",
    disaggregationDimensions: enterpriseDimensions,
    evidenceRequired: false,
    isOneTime: true,
    sortOrder: 110,
    baselines: [{ segmentKey: "overall", value: 0 }],
    targets: [
      { programmeYear: 0, value: MEL_OP11_MOBILISATION_TARGETS.overall },
      { programmeYear: 1, value: MEL_OP11_MOBILISATION_TARGETS.year1 },
      { programmeYear: 2, value: MEL_OP11_MOBILISATION_TARGETS.year2 },
      { programmeYear: 3, value: MEL_OP11_MOBILISATION_TARGETS.year3 },
    ],
  },
  {
    code: "OP1.1-CDP-IMPLEMENTED",
    resultCode: "OP1.1",
    resultLevel: "output",
    resultStatement: "MSEs mobilized",
    name: "Number of implemented Capacity Development Plans",
    unit: "count",
    sourceType: "system",
    frequency: "annual",
    aggregation: "distinct_count",
    disaggregationDimensions: enterpriseDimensions,
    evidenceRequired: false,
    isOneTime: true,
    sortOrder: 120,
    baselines: [{ segmentKey: "overall", value: 0 }],
    targets: [
      { programmeYear: 0, value: MEL_OP11_MOBILISATION_TARGETS.overall },
      { programmeYear: 1, value: MEL_OP11_MOBILISATION_TARGETS.year1 },
      { programmeYear: 2, value: MEL_OP11_MOBILISATION_TARGETS.year2 },
      { programmeYear: 3, value: MEL_OP11_MOBILISATION_TARGETS.year3 },
    ],
  },
  {
    code: "OP1.2-TRAINING-COMPLETION",
    resultCode: "OP1.2",
    resultLevel: "output",
    resultStatement: "MSE enterprise capacity enhanced",
    name: "Percentage of MSEs completing leadership, management and governance training",
    ...ratioDefinition("Enterprises completing the required training", "Enterprises assigned the required training"),
    unit: "percentage",
    sourceType: "integration",
    frequency: "quarterly",
    aggregation: "ratio",
    disaggregationDimensions: enterpriseDimensions,
    evidenceRequired: false,
    isOneTime: true,
    sortOrder: 140,
    baselines: [
      { segmentKey: "overall", value: 36 },
      { segmentKey: "track:foundation", value: 35 },
      { segmentKey: "track:acceleration", value: 38 },
    ],
    targets: [
      { programmeYear: 0, value: 100 },
      { programmeYear: 2, value: 90 },
      { programmeYear: 3, value: 100 },
    ],
  },
  {
    code: "OP1.2-IMPROVED-BUSINESS-PLANS",
    resultCode: "OP1.2",
    resultLevel: "output",
    resultStatement: "MSE enterprise capacity enhanced",
    name: "Percentage of MSEs with improved business plans",
    ...ratioDefinition("Enterprises with an approved improved business plan", "Eligible supported enterprises"),
    unit: "percentage",
    sourceType: "quarterly_enterprise_form",
    frequency: "quarterly",
    aggregation: "ratio",
    disaggregationDimensions: enterpriseDimensions,
    evidenceRequired: true,
    isOneTime: true,
    sortOrder: 150,
    baselines: [
      { segmentKey: "overall", value: 78 },
      { segmentKey: "track:foundation", value: 72 },
      { segmentKey: "track:acceleration", value: 87 },
    ],
    targets: [
      { programmeYear: 0, value: 100 },
      { programmeYear: 2, value: 90 },
      { programmeYear: 3, value: 100 },
    ],
  },
  {
    code: "OP1.2-TECHNOLOGY-ADOPTION",
    resultCode: "OP1.2",
    resultLevel: "output",
    resultStatement: "MSE enterprise capacity enhanced",
    name: "Percentage of enterprises adopting new technologies or innovations",
    ...ratioDefinition("Enterprises with approved new technology or innovation adoption", "Eligible supported enterprises"),
    unit: "percentage",
    sourceType: "quarterly_enterprise_form",
    frequency: "quarterly",
    aggregation: "ratio",
    disaggregationDimensions: enterpriseDimensions,
    evidenceRequired: true,
    isOneTime: false,
    sortOrder: 160,
    baselines: [
      { segmentKey: "overall", value: 78 },
      { segmentKey: "track:foundation", value: 72 },
      { segmentKey: "track:acceleration", value: 87 },
    ],
    targets: [
      { programmeYear: 0, value: 90 },
      { programmeYear: 2, value: 90 },
      { programmeYear: 3, value: 100, notes: "ITT annual target exceeds the overall target; confirm during Phase 1 review." },
    ],
  },
  {
    code: "OP1.2-NEW-PRODUCTS",
    resultCode: "OP1.2",
    resultLevel: "output",
    resultStatement: "MSE enterprise capacity enhanced",
    name: "Percentage of enterprises developing new products or services",
    ...ratioDefinition("Enterprises with an approved new product or service", "Eligible supported enterprises"),
    unit: "percentage",
    sourceType: "quarterly_enterprise_form",
    frequency: "quarterly",
    aggregation: "ratio",
    disaggregationDimensions: enterpriseDimensions,
    evidenceRequired: true,
    isOneTime: false,
    sortOrder: 170,
    unresolvedNotes: "The ITT label says number, while baseline and targets are percentages. Seeded as a percentage pending confirmation.",
    baselines: [
      { segmentKey: "overall", value: 57 },
      { segmentKey: "track:foundation", value: 59 },
      { segmentKey: "track:acceleration", value: 56 },
    ],
    targets: [
      { programmeYear: 0, value: 70 },
      { programmeYear: 2, value: 65 },
      { programmeYear: 3, value: 70 },
    ],
  },
  {
    code: "OP2.1-FINANCIAL-PLANS",
    resultCode: "OP2.1",
    resultLevel: "output",
    resultStatement: "Enterprises have increased access to financial services",
    name: "Percentage of enterprises with feasible financial plans",
    ...ratioDefinition("Enterprises with an approved feasible financial plan", "Eligible supported enterprises"),
    unit: "percentage",
    sourceType: "quarterly_enterprise_form",
    frequency: "quarterly",
    aggregation: "ratio",
    disaggregationDimensions: enterpriseDimensions,
    evidenceRequired: true,
    isOneTime: true,
    sortOrder: 200,
    baselines: [
      { segmentKey: "overall", value: 62 },
      { segmentKey: "track:foundation", value: 61 },
      { segmentKey: "track:acceleration", value: 64 },
    ],
    targets: [
      { programmeYear: 0, value: 80 },
      { programmeYear: 2, value: 70 },
      { programmeYear: 3, value: 80 },
    ],
  },
  {
    code: "OP2.1-FINANCIAL-LINKAGES",
    resultCode: "OP2.1",
    resultLevel: "output",
    resultStatement: "Enterprises have increased access to financial services",
    name: "Percentage of enterprises linked to financial services",
    ...ratioDefinition("Enterprises with an approved financial-service linkage", "Eligible supported enterprises"),
    unit: "percentage",
    sourceType: "quarterly_enterprise_form",
    frequency: "quarterly",
    aggregation: "ratio",
    disaggregationDimensions: enterpriseDimensions,
    evidenceRequired: true,
    isOneTime: false,
    sortOrder: 210,
    baselines: [
      { segmentKey: "overall", value: 23 },
      { segmentKey: "track:foundation", value: 16 },
      { segmentKey: "track:acceleration", value: 31 },
    ],
    targets: [
      { programmeYear: 0, value: 50 },
      { programmeYear: 2, value: 40 },
      { programmeYear: 3, value: 50 },
    ],
  },
  {
    code: "OP2.1-ACTIVE-INSURANCE",
    resultCode: "OP2.1",
    resultLevel: "output",
    resultStatement: "Enterprises have increased access to financial services",
    name: "Percentage of enterprises with an active insurance policy",
    ...ratioDefinition("Enterprises with an approved active insurance policy", "Eligible supported enterprises"),
    unit: "percentage",
    sourceType: "quarterly_enterprise_form",
    frequency: "quarterly",
    aggregation: "ratio",
    disaggregationDimensions: enterpriseDimensions,
    evidenceRequired: true,
    isOneTime: false,
    sortOrder: 220,
    baselines: [
      { segmentKey: "overall", value: 21 },
      { segmentKey: "track:foundation", value: 13 },
      { segmentKey: "track:acceleration", value: 31 },
    ],
    targets: [
      { programmeYear: 0, value: 42 },
      { programmeYear: 2, value: 35 },
      { programmeYear: 3, value: 42 },
    ],
  },
  {
    code: "OP2.1-INVESTOR-READINESS",
    resultCode: "OP2.1",
    resultLevel: "output",
    resultStatement: "Enterprises have increased access to financial services",
    name: "Percentage of enterprises completing investor-readiness training",
    ...ratioDefinition("Enterprises completing investor-readiness training", "Enterprises assigned the training"),
    unit: "percentage",
    sourceType: "integration",
    frequency: "quarterly",
    aggregation: "ratio",
    disaggregationDimensions: enterpriseDimensions,
    evidenceRequired: false,
    isOneTime: true,
    sortOrder: 230,
    unresolvedNotes: "The ITT label says number, while baseline and targets are percentages. Seeded as a percentage pending confirmation.",
    baselines: [
      { segmentKey: "overall", value: 33 },
      { segmentKey: "track:foundation", value: 23 },
      { segmentKey: "track:acceleration", value: 47 },
    ],
    targets: [
      { programmeYear: 0, value: 100 },
      { programmeYear: 2, value: 80 },
      { programmeYear: 3, value: 100 },
    ],
  },
  {
    code: "OP2.1-FINANCE-VALUE",
    resultCode: "OP2.1",
    resultLevel: "output",
    resultStatement: "Enterprises have increased access to financial services",
    name: "Value of financial services accessed by MSEs",
    definition: "Approved value of grants, matching grants, loans, or other configured finance accessed.",
    unit: "kes",
    sourceType: "quarterly_enterprise_form",
    frequency: "quarterly",
    aggregation: "sum",
    disaggregationDimensions: enterpriseDimensions,
    evidenceRequired: true,
    isOneTime: false,
    sortOrder: 240,
    baselines: [
      { segmentKey: "overall", value: 2400000 },
      { segmentKey: "track:foundation", value: 1480000 },
      { segmentKey: "track:acceleration", value: 6450000 },
    ],
    targets: [{ programmeYear: 0, value: 3400000 }],
  },
  {
    code: "OP2.2-MARKET-RESEARCH",
    resultCode: "OP2.2",
    resultLevel: "output",
    resultStatement: "Enterprises have increased access to market information",
    name: "Percentage of enterprises completing market research with documented findings",
    ...ratioDefinition("Enterprises with an approved market research report", "Eligible supported enterprises"),
    unit: "percentage",
    sourceType: "quarterly_enterprise_form",
    frequency: "quarterly",
    aggregation: "ratio",
    disaggregationDimensions: enterpriseDimensions,
    evidenceRequired: true,
    isOneTime: true,
    sortOrder: 250,
    baselines: [
      { segmentKey: "overall", value: 15 },
      { segmentKey: "track:foundation", value: 13 },
      { segmentKey: "track:acceleration", value: 18 },
    ],
    targets: [
      { programmeYear: 0, value: 100 },
      { programmeYear: 2, value: 80 },
      { programmeYear: 3, value: 100 },
    ],
  },
  {
    code: "OP2.2-MARKET-INTELLIGENCE",
    resultCode: "OP2.2",
    resultLevel: "output",
    resultStatement: "Enterprises have increased access to market information",
    name: "Percentage of enterprises accessing market-intelligence information",
    ...ratioDefinition("Enterprises with approved access to market-intelligence information", "Eligible supported enterprises"),
    unit: "percentage",
    sourceType: "quarterly_enterprise_form",
    frequency: "quarterly",
    aggregation: "ratio",
    disaggregationDimensions: enterpriseDimensions,
    evidenceRequired: false,
    isOneTime: false,
    sortOrder: 260,
    baselines: [
      { segmentKey: "overall", value: 75 },
      { segmentKey: "track:foundation", value: 73 },
      { segmentKey: "track:acceleration", value: 79 },
    ],
    targets: [
      { programmeYear: 0, value: 100 },
      { programmeYear: 2, value: 80 },
      { programmeYear: 3, value: 100 },
    ],
  },
  {
    code: "OP2.2-STRATEGIC-PARTNERSHIPS",
    resultCode: "OP2.2",
    resultLevel: "output",
    resultStatement: "Enterprises have increased access to market information",
    name: "Percentage of enterprises establishing a strategic partnership",
    ...ratioDefinition("Enterprises with an approved new strategic partnership", "Eligible supported enterprises"),
    unit: "percentage",
    sourceType: "quarterly_enterprise_form",
    frequency: "quarterly",
    aggregation: "ratio",
    disaggregationDimensions: enterpriseDimensions,
    evidenceRequired: true,
    isOneTime: false,
    sortOrder: 270,
    unresolvedNotes: "The ITT label says number per MSE, while baseline and targets are percentages.",
    baselines: [
      { segmentKey: "overall", value: 39 },
      { segmentKey: "track:foundation", value: 36 },
      { segmentKey: "track:acceleration", value: 43 },
    ],
    targets: [
      { programmeYear: 0, value: 60 },
      { programmeYear: 2, value: 50 },
      { programmeYear: 3, value: 60 },
    ],
  },
  {
    code: "OP2.2-NEW-MARKET-SEGMENTS",
    resultCode: "OP2.2",
    resultLevel: "output",
    resultStatement: "Enterprises have increased access to market information",
    name: "Percentage of enterprises serving more than three new market segments",
    ...ratioDefinition("Enterprises serving more than three approved new market segments", "Eligible supported enterprises"),
    unit: "percentage",
    sourceType: "quarterly_enterprise_form",
    frequency: "quarterly",
    aggregation: "ratio",
    disaggregationDimensions: enterpriseDimensions,
    evidenceRequired: false,
    isOneTime: false,
    sortOrder: 280,
    unresolvedNotes: "The ITT label says number, while baseline and targets are percentages.",
    baselines: [
      { segmentKey: "overall", value: 31 },
      { segmentKey: "track:foundation", value: 30 },
      { segmentKey: "track:acceleration", value: 33 },
    ],
    targets: [
      { programmeYear: 0, value: 50 },
      { programmeYear: 2, value: 40 },
      { programmeYear: 3, value: 50 },
    ],
  },
  {
    code: "OP3.1-ESG-REPORTS",
    resultCode: "OP3.1",
    resultLevel: "output",
    resultStatement: "MSEs have integrated circularity into their business models",
    name: "Percentage of MSEs with developed ESG sustainability reports",
    ...ratioDefinition("Enterprises with an approved ESG sustainability report", "Eligible supported enterprises"),
    unit: "percentage",
    sourceType: "quarterly_enterprise_form",
    frequency: "quarterly",
    aggregation: "ratio",
    disaggregationDimensions: enterpriseDimensions,
    evidenceRequired: true,
    isOneTime: true,
    sortOrder: 300,
    baselines: [
      { segmentKey: "overall", value: 11 },
      { segmentKey: "track:foundation", value: 7 },
      { segmentKey: "track:acceleration", value: 16 },
    ],
    targets: [
      { programmeYear: 0, value: 30 },
      { programmeYear: 2, value: 20 },
      { programmeYear: 3, value: 30 },
    ],
  },
  {
    code: "OP3.1-LIFE-CYCLE-ASSESSMENTS",
    resultCode: "OP3.1",
    resultLevel: "output",
    resultStatement: "MSEs have integrated circularity into their business models",
    name: "Number of completed product life-cycle assessments",
    unit: "count",
    sourceType: "quarterly_enterprise_form",
    frequency: "quarterly",
    aggregation: "distinct_count",
    disaggregationDimensions: enterpriseDimensions,
    evidenceRequired: true,
    isOneTime: true,
    sortOrder: 310,
    unresolvedNotes: "The ITT does not provide a baseline or target. MEL confirmation is required before activation.",
  },
  {
    code: "OP3.1-ECO-CERTIFICATION",
    resultCode: "OP3.1",
    resultLevel: "output",
    resultStatement: "MSEs have integrated circularity into their business models",
    name: "Percentage of MSEs with eco-certification or a compliance certificate",
    ...ratioDefinition("Enterprises with an approved valid eco-certification", "Eligible supported enterprises"),
    unit: "percentage",
    sourceType: "quarterly_enterprise_form",
    frequency: "quarterly",
    aggregation: "ratio",
    disaggregationDimensions: enterpriseDimensions,
    evidenceRequired: true,
    isOneTime: false,
    sortOrder: 320,
    baselines: [
      { segmentKey: "overall", value: 20 },
      { segmentKey: "track:foundation", value: 8 },
      { segmentKey: "track:acceleration", value: 35 },
    ],
    targets: [
      { programmeYear: 0, value: 40 },
      { programmeYear: 2, value: 30 },
      { programmeYear: 3, value: 40 },
    ],
  },
  {
    code: "OP3.2-SOCIAL-SAFEGUARDS",
    resultCode: "OP3.2",
    resultLevel: "output",
    resultStatement: "MSEs have inclusive social safeguard guidelines",
    name: "Percentage of MSEs with social safeguarding guidelines",
    ...ratioDefinition("Enterprises with approved social safeguarding guidelines", "Eligible supported enterprises"),
    unit: "percentage",
    sourceType: "quarterly_enterprise_form",
    frequency: "quarterly",
    aggregation: "ratio",
    disaggregationDimensions: enterpriseDimensions,
    evidenceRequired: true,
    isOneTime: true,
    sortOrder: 330,
    baselines: [
      { segmentKey: "overall", value: 60 },
      { segmentKey: "track:foundation", value: 58 },
      { segmentKey: "track:acceleration", value: 63 },
    ],
    targets: [
      { programmeYear: 0, value: 70 },
      { programmeYear: 2, value: 65 },
      { programmeYear: 3, value: 70 },
    ],
  },
  {
    code: "OP3.3-WASTE-RECYCLED",
    resultCode: "OP3.3",
    resultLevel: "output",
    resultStatement: "Increased recycling by waste-based enterprises",
    name: "Volume of waste collected and recycled by stream",
    definition: "Approved kilograms of waste collected and recycled, reported separately by waste stream.",
    unit: "kilograms",
    sourceType: "quarterly_enterprise_form",
    frequency: "quarterly",
    aggregation: "sum",
    disaggregationDimensions: ["track", "waste_stream", "county", "sector"],
    evidenceRequired: true,
    isOneTime: false,
    sortOrder: 340,
    baselines: [
      { segmentKey: "waste_stream:organic", value: 3100 },
      { segmentKey: "waste_stream:plastic", value: 1258 },
      { segmentKey: "waste_stream:paper", value: 15 },
      { segmentKey: "waste_stream:glass", value: 0 },
      { segmentKey: "waste_stream:e_waste", value: 0 },
      { segmentKey: "waste_stream:other", value: 2.5 },
    ],
    targets: [
      { programmeYear: 0, segmentKey: "waste_stream:organic", value: 5000 },
      { programmeYear: 0, segmentKey: "waste_stream:plastic", value: 2500 },
      { programmeYear: 0, segmentKey: "waste_stream:paper", value: 100 },
      { programmeYear: 0, segmentKey: "waste_stream:glass", value: 0 },
      { programmeYear: 0, segmentKey: "waste_stream:e_waste", value: 0 },
      { programmeYear: 0, segmentKey: "waste_stream:other", value: 2.5 },
    ],
  },
  {
    code: "OP4.1-POLICY-BRIEFS",
    resultCode: "OP4.1",
    resultLevel: "output",
    resultStatement: "County governments strengthen enabling policies and frameworks for MSEs",
    name: "Number of policy briefs developed",
    unit: "count",
    sourceType: "programme_mel_entry",
    frequency: "annual",
    aggregation: "sum",
    disaggregationDimensions: ["county"],
    evidenceRequired: true,
    isOneTime: false,
    sortOrder: 400,
    baselines: [{ segmentKey: "overall", value: 0 }],
    targets: [
      { programmeYear: 0, value: 4 },
      { programmeYear: 1, value: 1 },
      { programmeYear: 2, value: 2 },
      { programmeYear: 3, value: 1 },
    ],
  },
  {
    code: "OP4.1-ADVOCACY-FORUMS",
    resultCode: "OP4.1",
    resultLevel: "output",
    resultStatement: "County governments strengthen enabling policies and frameworks for MSEs",
    name: "Number of advocacy forums convened",
    unit: "count",
    sourceType: "programme_mel_entry",
    frequency: "annual",
    aggregation: "sum",
    disaggregationDimensions: ["county"],
    evidenceRequired: true,
    isOneTime: false,
    sortOrder: 410,
    unresolvedNotes: "The ITT overall target is 4 and annual distribution is 1+1+2=4, but the displayed total cell says 5.",
    baselines: [{ segmentKey: "overall", value: 0 }],
    targets: [
      { programmeYear: 0, value: 4 },
      { programmeYear: 1, value: 1 },
      { programmeYear: 2, value: 1 },
      { programmeYear: 3, value: 2 },
    ],
  },
  {
    code: "OP4.1-STAKEHOLDER-FORUMS",
    resultCode: "OP4.1",
    resultLevel: "output",
    resultStatement: "County governments strengthen enabling policies and frameworks for MSEs",
    name: "Number of policy research and stakeholder-engagement forums conducted",
    unit: "count",
    sourceType: "programme_mel_entry",
    frequency: "annual",
    aggregation: "sum",
    disaggregationDimensions: ["county"],
    evidenceRequired: true,
    isOneTime: false,
    sortOrder: 420,
    baselines: [{ segmentKey: "overall", value: 0 }],
    targets: [
      { programmeYear: 0, value: 6 },
      { programmeYear: 1, value: 2 },
      { programmeYear: 2, value: 2 },
      { programmeYear: 3, value: 2 },
    ],
  },
  {
    code: "OP4.1-PPPS",
    resultCode: "OP4.1",
    resultLevel: "output",
    resultStatement: "County governments strengthen enabling policies and frameworks for MSEs",
    name: "Number of public-private partnerships facilitated",
    unit: "count",
    sourceType: "programme_mel_entry",
    frequency: "annual",
    aggregation: "sum",
    disaggregationDimensions: ["county"],
    evidenceRequired: true,
    isOneTime: false,
    sortOrder: 430,
    baselines: [{ segmentKey: "overall", value: 0 }],
    targets: [
      { programmeYear: 0, value: 5 },
      { programmeYear: 1, value: 1 },
      { programmeYear: 2, value: 2 },
      { programmeYear: 3, value: 2 },
    ],
  },
  {
    code: "OP4.1-POLICIES-ADOPTED",
    resultCode: "OP4.1",
    resultLevel: "output",
    resultStatement: "County governments strengthen enabling policies and frameworks for MSEs",
    name: "Number of policies or frameworks adopted and implemented",
    unit: "count",
    sourceType: "programme_mel_entry",
    frequency: "annual",
    aggregation: "sum",
    disaggregationDimensions: ["county"],
    evidenceRequired: true,
    isOneTime: false,
    sortOrder: 440,
    baselines: [{ segmentKey: "overall", value: 0 }],
    targets: [
      { programmeYear: 0, value: 3 },
      { programmeYear: 1, value: 0 },
      { programmeYear: 2, value: 1 },
      { programmeYear: 3, value: 2 },
    ],
  },
];

export function validateMelIttSeed(seed: MelSeedIndicator[] = MEL_ITT_SEED): string[] {
  const issues: string[] = [];
  const codes = new Set<string>();

  for (const indicator of seed) {
    if (codes.has(indicator.code)) issues.push(`Duplicate indicator code: ${indicator.code}`);
    codes.add(indicator.code);

    if (indicator.aggregation === "ratio" && (!indicator.numeratorDefinition || !indicator.denominatorDefinition)) {
      issues.push(`Ratio indicator lacks numerator/denominator: ${indicator.code}`);
    }
    for (const target of indicator.targets ?? []) {
      if (target.value === undefined && !target.valueText) {
        issues.push(`Target has no value: ${indicator.code} year ${target.programmeYear}`);
      }
    }
    for (const baseline of indicator.baselines ?? []) {
      if (baseline.value === undefined && !baseline.valueText) {
        issues.push(`Baseline has no value: ${indicator.code} ${baseline.segmentKey}`);
      }
    }
  }

  return issues;
}
